### ISSUE TITLE
Test Suite blocks (`describeAndIt`) are repeated in the report

### ISSUE THREAD

**Issue by mayankshukla94** [webdriverio-community/wdio-html-reporter#74] opened 2021-09-24 13:10 UTC
### Description

When I'm executing nesting `describeAndIt` blocks then in the master report, Test Suite blocks are repeated.

For e.g.
```
describe('Suite 1', () => {
  describe('Suite 2', () => {
    it('test 1', async () => {
      utility.logMessage('test 1 block');
    });

    it('test 2', async () => {
      utility.logMessage('test 2 block');
    });
  });

  describe('Suite 3', () => {
    it('test 3', async () => {
      utility.logMessage('test 3 block');
    });
  });
});
```
### Spec Reporter
![image](https://user-images.githubusercontent.com/40030809/134679025-8ef7b5e9-82a9-4782-80dc-1f96489bf053.png)

**Comment by rpii** [comment] 2021-09-25 16:08
what version?  that was fixed in wdio-html-nice-reporter

**Comment by mayankshukla94** [comment] 2021-09-25 16:19
"wdio-html-nice-reporter": "^7.8.5",
"@rpii/wdio-report-events" : "^0.1.4"

**Comment by rpii** [comment] 2021-09-25 16:39
can you post the json file  that was generated?

**Comment by mayankshukla94** [comment] 2021-09-26 04:21
[master-report.zip](https://github.com/rpii/wdio-html-reporter/files/7230709/master-report.zip)
Please find the json report

**Comment by mayankshukla94** [comment] 2021-09-28 18:12
Hello @rpii 
Did you get a chance to check this json report?

**Comment by rpii** [comment] 2021-09-28 20:12
Thanks for providing it.  I havent had a chance and wont be able to look at
it probably until later this week.

Rich

**Comment by mayankshukla94** [comment] 2021-09-29 05:27
Sure thanks!

**Comment by arun04arun95** [comment] 2021-10-01 13:28
Having the same issue, test results are repeating in the reports.

**Comment by rpii** [comment] 2021-10-01 20:14
Well I am not sure what is going on at the  moment.
I see replicated tests in the json,  which the reporter doesnt generate,
it comes for the test executor

line 192

                "uid": "test-10-0",
                "cid": "0-0",
                "title": "test 1",
                "fullTitle": "Suite 1 Suite 2 test 1",

line 490

            "uid": "test-10-0",
            "cid": "0-0",
            "title": "test 1",
            "fullTitle": "Suite 1 Suite 2 test 1",

So,  the report is showing what its supposed to.

should not have replicated uid or cid in any test.

I will look further at this...



  Fri, Sep 24, 2021 at 6:11 AM Mayank Shukla ***@***.***>
wrote:

**Comment by mayankshukla94** [comment] 2021-12-04 15:51
Hello @rpii ,

We debugged the code to find the root cause of this issue and noticed that even for nested suites (`describe` block inside `describe` block), the code was adding a separate entry into the `reports.suites` array. Hence, duplicate entries for nested suites were getting generated in the `master-report`.

We added a condition in `createReport()` function of `reportAggregator.ts` to check if the `suite` does not have any parent then only proceed further. And this worked absolutely fine. 

I have raised a PR [Fix duplicate suites in the Master report](https://github.com/rpii/wdio-html-reporter/pull/76). 
Could you please check the PR

cc: @abime

**Comment by rpii** [comment] 2021-12-04 16:48
Thank you.  I will look at this

**Comment by rpii** [comment] 2021-12-05 01:23
HI,

I have looked at this and it works for cases without nested suites but
fails for the cucumber test I have.  Cucumber has nested suites and tests.
do you have a small test case I can use to get with to look at further?

Rich

**Comment by mayankshukla94** [comment] 2021-12-05 10:19
Hi @rpii ,

Thanks for checking the code.

I ran below spec file to fix this issue:

```
describe('Suite 1', () => {
  describe('Suite 2', () => {
    it('test 1', async () => {
      console.log('test 1 block');
    });

    it('test 2', async () => {
      console.log('test 2 block');
    });
  });

  describe('Suite 3', () => {
    it('test 3', async () => {
      console.log('test 3 block');
    });

    describe('Suite 4', () => {
        describe('Suite 5', () => {
            it('test 5', async() => {
                console.log('test 5 block');
            });
        });
    });
  });
});
```

**Comment by rpii** [comment] 2021-12-05 16:32
Thanks I will look at it

**Comment by rpii** [comment] 2021-12-05 18:10
do you mind sending me the mocharc.json that has the setup of the
reporter?  Or whatever way you are using
thanks
Rich

**Comment by mayankshukla94** [comment] 2021-12-06 07:06
Hi @rpii ,

We do not use mocharc.json. Instead we use package.json.

Let us know if you need any further information on analyzing the issue. 

```
{
  "name": "test-automation",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "prepare": "husky install"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "imports": {
    "#lib": "./lib/index.js",
    "#testdata": "./testdata/index.js"
  },
  "dependencies": {
    "@rpii/wdio-report-events": "^0.1.4",
    "@wdio/cli": "^7.7.4",
    "@wdio/reporter": "^7.7.5",
    "moment": "^2.29.1",
    "properties-reader": "^2.2.0",
    "string-format": "^2.0.0",
    "wdio-html-nice-reporter": "^7.8.5"
  },
  "devDependencies": {
    "@babel/cli": "^7.14.5",
    "@babel/core": "^7.14.6",
    "@babel/preset-env": "^7.14.7",
    "@babel/register": "^7.14.5",
    "@wdio/local-runner": "^7.7.4",
    "@wdio/mocha-framework": "^7.7.4",
    "@wdio/spec-reporter": "^7.7.3",
    "chai": "^4.3.4",
    "chromedriver": "^96.0.0",
    "husky": "^7.0.1",
    "lint-staged": "^12.0.2",
    "prettier": "2.3.2",
    "wdio-chromedriver-service": "^7.2.0"
  },
  "husky": {
    "hooks": {
      "pre-commit": "lint-staged"
    }
  },
  "lint-staged": {
    "**/*": "prettier --write --ignore-unknown"
  }
}
```

**Comment by rpii** [comment] 2021-12-06 22:34
Ok,  i now see what the issue is.  it take a little work to fix but needs
to be done.

thanks
Rich

**Comment by rpii** [comment] 2021-12-07 03:44
I published a fix for this issue for you to test.  It is npm  version 7.9.0
Could you please try it?

thanks
Rich

**Comment by abime** [comment] 2021-12-07 06:02
Thanks @rpii ,
@mayankshukla94 and I can collaborate for this and check if the issue is fixed.

**Comment by mayankshukla94** [comment] 2021-12-07 09:24
Hi @rpii 

It is working fine. 

Thanks for your help!

You can consider closing this PR https://github.com/rpii/wdio-html-reporter/pull/76 as the issue is already fixed.

cc: @abime

**Comment by rpii** [comment] 2021-12-07 16:06
Ok great.  thanks for all the collaboratio.

**Closed as completed by rpii** 2021-12-07 16:06 UTC
